{{- $CHART_NAME := .Values.service.app_name | default .Chart.Name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Revision }}-configmap
  labels:
    {{- include "mychart.labels" . | indent 4 }}
data:
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}
  release_name: {{ .Release.Name }}
  release_revision: {{ .Release.Revision }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
{{ include "mychart.app" . | indent 2 }}
