apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gcp
spec:
  acme:
    email: admin@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: gclouddnsissuersecret
    solvers:
      - dns01:
          cloudDNS:
            project: your_gcp_project_id
            serviceAccountSecretRef:
              name: gcp-dns-key
              key: dns01-solver.json
