apiVersion: v2
name: kafka-ui
description: A Helm chart for UI for Apache Kafka (kafka-ui) — a web UI for monitoring and managing Apache Kafka clusters
type: application
version: 0.7.2
appVersion: 0.7.2
home: https://github.com/logic3579/helm-charts
icon: https://raw.githubusercontent.com/provectus/kafka-ui/master/documentation/images/kafka-ui-logo.png
maintainers:
  - name: logic3579
    url: https://github.com/logic3579/helm-charts
keywords:
  - kafka
  - kafka-ui
  - monitoring
  - messaging
  - streaming
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Upstream Project
      url: https://github.com/kafbat/kafka-ui
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix chart icon URL
dependencies:
  - name: common
    version: "0.2.0"
    repository: "file://../common"
