apiVersion: v1
kind: ConfigMap
metadata:
  name: global-run
data:
  run.sh: |-
    #!/bin/bash
    set -x

    if [ "$DEBUG" = "true" ]; then
        tail -f /dev/null
    fi

    APP_NAME=${APP_NAME}
    APP_TYPE=${APP_TYPE}
    APP_LANG=${APP_LANG}

    case "$APP_TYPE" in
        frontend)
            /bin/sh -c 'nginx -g "daemon off;"'
            ;;
        backend)
            case "$APP_LANG" in
                GOLANG)
                    /app/main "${ARGS}"
                    ;;
                JAVA)
                    java \
                        -XX:InitialRAMPercentage=60.0 \
                        -XX:MaxRAMPercentage=90.0 \
                        -XX:MinRAMPercentage=60.0 \
                        -XX:+UseG1GC \
                        -XX:+ExplicitGCInvokesConcurrent \
                        -XX:+UseContainerSupport \
                        -XX:MaxGCPauseMillis=200 \
                        -jar /app/app.jar \
                        --server.port="${SERVER_PORT:-8080}" \
                        "$JAVA_OPTS" \
                        "${ARGS}"
                    ;;
            esac
            ;;
    esac
