apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana
  namespace: lgtm
spec:
  gateways:
    - istio-ingress/external-gateway
  hosts:
    - grafana.example.com
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: grafana.lgtm.svc.cluster.local
            port:
              number: 80
