apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mimir-gateway
  namespace: lgtm
spec:
  gateways:
    - istio-ingress/internal-gateway
  hosts:
    - mimir-gateway.example.com
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: mimir-gateway.lgtm.svc.cluster.local
            port:
              number: 80
