apiVersion: v2
name: go-app
description: A generic Helm chart for Go application deployment
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/logic3579/helm-charts
maintainers:
  - name: Logic
    url: https://github.com/logic3579/helm-charts
keywords:
  - go
  - golang
  - backend
  - microservice
dependencies:
  - name: common
    version: ">=0.1.0"
    repository: "file://../common"
