# # collect interval
# interval = 15

[[instances]]
# kubelete metrics
urls = ["https://127.0.0.1:10250/metrics"]
bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
use_tls = true
insecure_skip_verify = true
url_label_key = "instance"
url_label_value = "{{.Host}}"
# if you use dashboards, do not delete this label
labels = {job="categraf"}

[[instances]]
# kube-state-metrics
urls = ["http://kube-state-metrics:8080/metrics"]
use_tls = false
url_label_key = "instance"
url_label_value = "{{.Host}}"
# if you use dashboards, do not delete this label
labels = {job="categraf"}

[[instances]]
# prometheus-mysql-exporter
urls = ["http://prometheus-mysql-exporter:9104/metrics"]
use_tls = false
url_label_key = "instance"
url_label_value = "{{.Host}}"
# if you use dashboards, do not delete this label
labels = {job="categraf"}
