apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: mgmt
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redisinsight
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redisinsight
      namespace: mgmt
    spec:
      containers:
        - env:
            - name: SERVICE_NAME
              value: redisinsight
            - name: RITRUSTEDORIGINS
              value: http://redisinsight.example.com,https://redisinsight.example.com
          image: redislabs/redisinsight:latest
          imagePullPolicy: IfNotPresent
          name: redisinsight
          ports:
            - containerPort: 8001
              name: port-8001
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisinsight
  name: redisinsight
  namespace: mgmt
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-8080
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: redisinsight
  sessionAffinity: None
  type: ClusterIP
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: redisinsight
#  namespace: mgmt
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: redisinsight.example.com
#      http:
#        paths:
#          - backend:
#              service:
#                name: redisinsight
#                port:
#                  number: 8001
#            path: /
#            pathType: ImplementationSpecific
#status:
#  loadBalancer:
#    ingress:
#      - ip: 1.1.1.1
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: redisinsight
  namespace: mgmt
spec:
  gateways:
    - istio-ingress/gateway-internal
  hosts:
    - redisinsight.example.com
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: redisinsight.mgmt.svc.cluster.local
            port:
              number: 8001
