name: Release Charts

on:
  push:
    branches:
      - main

env:
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name ${{ env.REPO_OWNER }}
          git config user.email "${{ env.REPO_OWNER }}@duck.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
